# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .net framework env
        uses: vrnobody/Setup-DotNetFrameworkEnv@v1.2.6

      - name: Restore Nuget packages
        run: nuget restore BikeDistributor.sln

      - name: Build solution
        run: msbuild BikeDistributor.sln -p:Configuration=Release

      - name: Run unit tests
        run: |
          function Invoke-VSTest {
            & "vstest.console.exe" $args
            if(-not $?){ throw "fail!" }
          }
          Invoke-VSTest "BikeDistributor.Test/bin/Release/BikeDistributor.Test.dll"
